package com.company;// Generated by GraphWalker (http://www.graphwalker.org)

import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "LetgoMini.json")
public interface LetgoMini {

    @Edge()
    void e_openHomePage();

    @Vertex()
    void v_Start();

    @Vertex()
    void v_HomePage();
}
